import { and, desc, eq, gte } from "drizzle-orm";
import { db } from "../../db/index.js";
import {
  alerts,
  caseEvents,
  transactions,
  users,
  type AlertSeverity,
  type AnomalyCategory,
  type Provider,
} from "../../db/schema.js";
import { AppError } from "../../middleware/errorHandler.js";

export async function getRecentTransactions(
  agentId: string,
  provider: Provider | undefined,
  hours: number,
  referenceTime: Date,
) {
  const since = new Date(referenceTime.getTime() - hours * 60 * 60 * 1000);
  const conditions = [eq(transactions.agentId, agentId), gte(transactions.occurredAt, since)];
  if (provider) conditions.push(eq(transactions.provider, provider));

  return db
    .select()
    .from(transactions)
    .where(and(...conditions))
    .orderBy(desc(transactions.occurredAt));
}

export async function getLatestTransactionTime(agentId: string): Promise<Date> {
  const [row] = await db
    .select({ occurredAt: transactions.occurredAt })
    .from(transactions)
    .where(eq(transactions.agentId, agentId))
    .orderBy(desc(transactions.occurredAt))
    .limit(1);

  return row?.occurredAt ?? new Date();
}

async function getBlockOpsOwner(blockId: string): Promise<string | null> {
  const [row] = await db
    .select({ id: users.id })
    .from(users)
    .where(and(eq(users.role, "ops"), eq(users.blockId, blockId)))
    .limit(1);

  return row?.id ?? null;
}

interface UpsertAlertInput {
  type: "liquidity" | "anomaly";
  agentId: string;
  blockId: string;
  provider?: Provider | null;
  severity: AlertSeverity;
  title: string;
  description: string;
  banglishSummary: string;
  evidence: unknown;
  confidence: number;
  predictedShortageAt?: Date | null;
  category?: AnomalyCategory | null;
  votes?: unknown;
  scenarioTag?: string | null;
}

export async function upsertAlert(input: UpsertAlertInput) {
  const conditions = [
    eq(alerts.agentId, input.agentId),
    eq(alerts.type, input.type),
    eq(alerts.status, "open"),
  ];
  if (input.provider) conditions.push(eq(alerts.provider, input.provider));
  if (input.category) conditions.push(eq(alerts.category, input.category));

  const [existing] = await db
    .select()
    .from(alerts)
    .where(and(...conditions))
    .limit(1);

  if (existing) {
    const [updated] = await db
      .update(alerts)
      .set({
        severity: input.severity,
        title: input.title,
        description: input.description,
        banglishSummary: input.banglishSummary,
        evidence: input.evidence,
        confidence: input.confidence.toFixed(3),
        predictedShortageAt: input.predictedShortageAt ?? null,
        votes: input.votes ?? undefined,
        scenarioTag: input.scenarioTag ?? null,
      })
      .where(eq(alerts.id, existing.id))
      .returning();

    return { alert: updated!, created: false };
  }

  const ownerUserId = await getBlockOpsOwner(input.blockId);

  const [created] = await db
    .insert(alerts)
    .values({
      type: input.type,
      severity: input.severity,
      agentId: input.agentId,
      blockId: input.blockId,
      provider: input.provider ?? null,
      title: input.title,
      description: input.description,
      banglishSummary: input.banglishSummary,
      evidence: input.evidence,
      confidence: input.confidence.toFixed(3),
      predictedShortageAt: input.predictedShortageAt ?? null,
      category: input.category ?? null,
      votes: input.votes ?? null,
      scenarioTag: input.scenarioTag ?? null,
      ownerUserId,
    })
    .returning();

  await db.insert(caseEvents).values({
    alertId: created!.id,
    type: "created",
    note: ownerUserId
      ? "Auto-generated by the analysis pipeline and routed to the block's operations team."
      : "Auto-generated by the analysis pipeline. No operations user is provisioned for this block yet.",
  });

  return { alert: created!, created: true };
}

const ALERT_ACTIONS = {
  acknowledge: "acknowledged",
  escalate: "escalated",
  resolve: "resolved",
} as const;

export type AlertAction = keyof typeof ALERT_ACTIONS;

export async function applyAlertAction(params: {
  alertId: string;
  blockId: string;
  action: AlertAction;
  actorUserId: string;
  note?: string;
}) {
  const [alert] = await db.select().from(alerts).where(eq(alerts.id, params.alertId));
  if (!alert) throw new AppError("Alert not found", 404);
  if (alert.blockId !== params.blockId) {
    throw new AppError("Alert belongs to a different block", 403);
  }

  const newStatus = ALERT_ACTIONS[params.action];

  const [updated] = await db
    .update(alerts)
    .set({
      status: newStatus,
      resolvedAt: params.action === "resolve" ? new Date() : alert.resolvedAt,
    })
    .where(eq(alerts.id, alert.id))
    .returning();

  await db.insert(caseEvents).values({
    alertId: alert.id,
    type: newStatus,
    actorUserId: params.actorUserId,
    note: params.note ?? null,
  });

  return updated!;
}
