import { and, desc, eq, gte } from "drizzle-orm";
import { db } from "../../db/index.js";
import {
  alerts,
  caseEvents,
  transactions,
  users,
  type AlertSeverity,
  type AnomalyCategory,
  type Provider,
} from "../../db/schema.js";

export async function getRecentTransactions(
  agentId: string,
  provider: Provider | undefined,
  hours: number,
  referenceTime: Date,
) {
  const since = new Date(referenceTime.getTime() - hours * 60 * 60 * 1000);
  const conditions = [eq(transactions.agentId, agentId), gte(transactions.occurredAt, since)];
  if (provider) conditions.push(eq(transactions.provider, provider));

  return db
    .select()
    .from(transactions)
    .where(and(...conditions))
    .orderBy(desc(transactions.occurredAt));
}

export async function getLatestTransactionTime(agentId: string): Promise<Date> {
  const [row] = await db
    .select({ occurredAt: transactions.occurredAt })
    .from(transactions)
    .where(eq(transactions.agentId, agentId))
    .orderBy(desc(transactions.occurredAt))
    .limit(1);

  return row?.occurredAt ?? new Date();
}

async function getBlockOpsOwner(blockId: string): Promise<string | null> {
  const [row] = await db
    .select({ id: users.id })
    .from(users)
    .where(and(eq(users.role, "ops"), eq(users.blockId, blockId)))
    .limit(1);

  return row?.id ?? null;
}

interface UpsertAlertInput {
  type: "liquidity" | "anomaly";
  agentId: string;
  blockId: string;
  provider?: Provider | null;
  severity: AlertSeverity;
  title: string;
  description: string;
  evidence: unknown;
  confidence: number;
  predictedShortageAt?: Date | null;
  category?: AnomalyCategory | null;
  votes?: unknown;
}

export async function upsertAlert(input: UpsertAlertInput) {
  const conditions = [
    eq(alerts.agentId, input.agentId),
    eq(alerts.type, input.type),
    eq(alerts.status, "open"),
  ];
  if (input.provider) conditions.push(eq(alerts.provider, input.provider));
  if (input.category) conditions.push(eq(alerts.category, input.category));

  const [existing] = await db
    .select()
    .from(alerts)
    .where(and(...conditions))
    .limit(1);

  if (existing) {
    const [updated] = await db
      .update(alerts)
      .set({
        severity: input.severity,
        title: input.title,
        description: input.description,
        evidence: input.evidence,
        confidence: input.confidence.toFixed(3),
        predictedShortageAt: input.predictedShortageAt ?? null,
        votes: input.votes ?? undefined,
      })
      .where(eq(alerts.id, existing.id))
      .returning();

    return { alert: updated!, created: false };
  }

  const ownerUserId = await getBlockOpsOwner(input.blockId);

  const [created] = await db
    .insert(alerts)
    .values({
      type: input.type,
      severity: input.severity,
      agentId: input.agentId,
      blockId: input.blockId,
      provider: input.provider ?? null,
      title: input.title,
      description: input.description,
      evidence: input.evidence,
      confidence: input.confidence.toFixed(3),
      predictedShortageAt: input.predictedShortageAt ?? null,
      category: input.category ?? null,
      votes: input.votes ?? null,
      ownerUserId,
    })
    .returning();

  await db.insert(caseEvents).values({
    alertId: created!.id,
    type: "created",
    note: ownerUserId
      ? "Auto-generated by the analysis pipeline and routed to the block's operations team."
      : "Auto-generated by the analysis pipeline. No operations user is provisioned for this block yet.",
  });

  return { alert: created!, created: true };
}
